name: 'compose-editor'
description: 'Edit docker-compose files'
author: 'gabor-kovac'

inputs:
  command:
    description: 'Command to perform (print, set, add, delete)'
    required: true
    default: 'print'
  inputFile:
    description: 'Input docker-compose.yml file'
    required: true
    default: 'docker-compose.yml'
  outputFile:
    description: 'Output edited compose to this file, if not provided will output to stdout'
    required: false
  verbose:
    description: 'Print verbose output'
    required: false
    default: false
  service:
    description: 'Docker compose service (ex. mqtt)'
    required: true
    default: null
  attribute:
    description: 'Service's attribute (ex. restart)'
    required: false
    default: null
  value:
    description: 'Value of the attribute (ex. always), hjson format'
    required: false
    default: null

outputs:
  yml:
    description: 'Output compose in yml format'
  print:
    description: 'Output of print command'

runs:
  using: node20
  main: dist/index.js
